<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MenuSeeder extends Seeder
{
    public function run()
    {
        // Datos de ejemplo para menús del sistema GMV
        $menus = [
            // MENÚS PRINCIPALES (Nivel 1)
            [
                'icono' => 'fas fa-tachometer-alt',
                'menu' => 'Dashboard',
                'id_superior' => null,
                'nivel' => 1,
                'ruta' => 'dashboard',
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'icono' => 'fas fa-car',
                'menu' => 'Gestión de Vehículos',
                'id_superior' => null,
                'nivel' => 1,
                'orden' => 2,
                'url' => null, // Menú contenedor
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'icono' => 'fas fa-users',
                'menu' => 'Gestión de Conductores',
                'id_superior' => null,
                'nivel' => 1,
                'orden' => 3,
                'url' => null, // Menú contenedor
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'icono' => 'fas fa-gas-pump',
                'menu' => 'Control de Combustible',
                'id_superior' => null,
                'nivel' => 1,
                'orden' => 4,
                'url' => null, // Menú contenedor
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'icono' => 'fas fa-tools',
                'menu' => 'Mantenimiento',
                'id_superior' => null,
                'nivel' => 1,
                'orden' => 5,
                'url' => null, // Menú contenedor
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'icono' => 'fas fa-chart-bar',
                'menu' => 'Reportes y Análisis',
                'id_superior' => null,
                'nivel' => 1,
                'orden' => 6,
                'url' => null, // Menú contenedor
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'icono' => 'fas fa-cog',
                'menu' => 'Configuración',
                'id_superior' => null,
                'nivel' => 1,
                'orden' => 7,
                'url' => null, // Menú contenedor
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],

            // SUBMENÚS DE GESTIÓN DE VEHÍCULOS (Nivel 2)
            [
                'id' => 8,
                'icono' => 'fas fa-list',
                'menu' => 'Lista de Vehículos',
                'id_superior' => 2,
                'nivel' => 2,
                'orden' => 1,
                'url' => 'vehiculos',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'icono' => 'fas fa-plus',
                'menu' => 'Registrar Vehículo',
                'id_superior' => 2,
                'nivel' => 2,
                'orden' => 2,
                'url' => 'vehiculos/create',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'icono' => 'fas fa-exchange-alt',
                'menu' => 'Asignación de Vehículos',
                'id_superior' => 2,
                'nivel' => 2,
                'orden' => 3,
                'url' => 'asignacion-vehiculos',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'icono' => 'fas fa-file-alt',
                'menu' => 'Documentación',
                'id_superior' => 2,
                'nivel' => 2,
                'orden' => 4,
                'url' => 'vehiculos/documentos',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],

            // SUBMENÚS DE GESTIÓN DE CONDUCTORES (Nivel 2)
            [
                'id' => 12,
                'icono' => 'fas fa-list',
                'menu' => 'Lista de Conductores',
                'id_superior' => 3,
                'nivel' => 2,
                'orden' => 1,
                'url' => 'conductores',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 13,
                'icono' => 'fas fa-user-plus',
                'menu' => 'Registrar Conductor',
                'id_superior' => 3,
                'nivel' => 2,
                'orden' => 2,
                'url' => 'conductores/create',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 14,
                'icono' => 'fas fa-id-card',
                'menu' => 'Documentación',
                'id_superior' => 3,
                'nivel' => 2,
                'orden' => 3,
                'url' => 'conductores/documentos',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],

            // SUBMENÚS DE CONTROL DE COMBUSTIBLE (Nivel 2)
            [
                'id' => 15,
                'icono' => 'fas fa-clipboard-list',
                'menu' => 'Registros de Combustible',
                'id_superior' => 4,
                'nivel' => 2,
                'orden' => 1,
                'url' => 'registro-combustible',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 16,
                'icono' => 'fas fa-plus-circle',
                'menu' => 'Nuevo Registro',
                'id_superior' => 4,
                'nivel' => 2,
                'orden' => 2,
                'url' => 'registro-combustible/create',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 17,
                'icono' => 'fas fa-chart-line',
                'menu' => 'Estadísticas de Consumo',
                'id_superior' => 4,
                'nivel' => 2,
                'orden' => 3,
                'url' => 'registro-combustible/estadisticas',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],

            // SUBMENÚS DE MANTENIMIENTO (Nivel 2)
            [
                'id' => 18,
                'icono' => 'fas fa-wrench',
                'menu' => 'Solicitudes de Mantenimiento',
                'id_superior' => 5,
                'nivel' => 2,
                'orden' => 1,
                'url' => 'solicitudes',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 19,
                'icono' => 'fas fa-calendar-check',
                'menu' => 'Programación de Mantenimiento',
                'id_superior' => 5,
                'nivel' => 2,
                'orden' => 2,
                'url' => 'mantenimiento/programacion',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 20,
                'icono' => 'fas fa-history',
                'menu' => 'Historial de Mantenimiento',
                'id_superior' => 5,
                'nivel' => 2,
                'orden' => 3,
                'url' => 'mantenimiento/historial',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],

            // SUBMENÚS DE REPORTES (Nivel 2)
            [
                'id' => 21,
                'icono' => 'fas fa-file-pdf',
                'menu' => 'Reportes de Vehículos',
                'id_superior' => 6,
                'nivel' => 2,
                'orden' => 1,
                'url' => 'reportes/vehiculos',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 22,
                'icono' => 'fas fa-chart-pie',
                'menu' => 'Análisis de Combustible',
                'id_superior' => 6,
                'nivel' => 2,
                'orden' => 2,
                'url' => 'reportes/combustible',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 23,
                'icono' => 'fas fa-download',
                'menu' => 'Exportar Datos',
                'id_superior' => 6,
                'nivel' => 2,
                'orden' => 3,
                'url' => 'reportes/exportar',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],

            // SUBMENÚS DE CONFIGURACIÓN (Nivel 2)
            [
                'id' => 24,
                'icono' => 'fas fa-users-cog',
                'menu' => 'Gestión de Usuarios',
                'id_superior' => 7,
                'nivel' => 2,
                'orden' => 1,
                'url' => 'admin/usuarios',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 25,
                'icono' => 'fas fa-shield-alt',
                'menu' => 'Roles y Permisos',
                'id_superior' => 7,
                'nivel' => 2,
                'orden' => 2,
                'url' => 'admin/roles',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 26,
                'icono' => 'fas fa-sitemap',
                'menu' => 'Gestión de Menús',
                'id_superior' => 7,
                'nivel' => 2,
                'orden' => 3,
                'url' => 'menu',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 27,
                'icono' => 'fas fa-sliders-h',
                'menu' => 'Configuración General',
                'id_superior' => 7,
                'nivel' => 2,
                'orden' => 4,
                'url' => 'admin/configuracion',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],

            // SUBMENÚS DE TERCER NIVEL (Ejemplos)
            [
                'id' => 28,
                'icono' => 'fas fa-plus',
                'menu' => 'Crear Usuario',
                'id_superior' => 24,
                'nivel' => 3,
                'orden' => 1,
                'url' => 'admin/usuarios/create',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 29,
                'icono' => 'fas fa-list',
                'menu' => 'Lista de Usuarios',
                'id_superior' => 24,
                'nivel' => 3,
                'orden' => 2,
                'url' => 'admin/usuarios',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 30,
                'icono' => 'fas fa-user-shield',
                'menu' => 'Permisos Especiales',
                'id_superior' => 25,
                'nivel' => 3,
                'orden' => 1,
                'url' => 'admin/roles/permisos',
                'activo' => 1,
                'usuario_crea' => 1,
                'fecha_registra' => date('Y-m-d H:i:s'),
            ],
        ];

        // Insertar los datos usando el Query Builder
        $this->db->table('menus')->insertBatch($menus);

        echo "Seeder de menús ejecutado exitosamente. Se insertaron " . count($menus) . " menús.\n";
    }
}
